name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.ref }}

      - name: Set Version
        run: npm --no-git-tag-version version 1.0.${{ steps.buildnumber.outputs.build_number }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install
#
#      - name: Lint
#        run: npm run lint
#
#      - name: Test
#        run: npm test
#        env: { CI: true }

      - name: Production Build
        run: npm ci && npm run build
        env: { CI: true }

      - name: Package
        run: npm pack

      - name: Authenticate with NPM registry
        if: github.ref == 'refs/heads/master'
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish NPM package
        if: github.ref == 'refs/heads/master'
        run: npm publish --access public
